api: uvicorn --port 8000 compare:app --reload
api: uvicorn --port 8001 validate:app --reload
api: uvicorn --port 6003 statsFromShardedDB:app --reload
api: uvicorn --port 5001 track:app --reload
api: uvicorn --port 5003 gameService:app --reload
